---
title: "Parting remarks"
subtitle: "Reproducible Computing <br> @ JSM 2019"
author: "Colin Rundel"
date: "July 27, 2019"
output:
  xaringan::moon_reader:
    css: "../slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

## Reproducibility ladder

Aim to go at least a little higher in your next project in at least one area

1. Scriptability
2. Literate Programming
3. Version Control
4. Automation

---

## R Markdown tips / resources

- R Markdown cheatsheet: https://www.rstudio.com/resources/cheatsheets/
- R Markdown document should be in your root directory
- Do not set a working directory in your R Markdown document
  - Actually, don't ever use `setwd()`
  - See the `here` package for an alternative approach

---

## GitHub tips / resources

- It's pretty easy to convert your repo to a website
  - Go to Settings and then Enable GitHub pages
  - Lots of Packages to help create a nice webpage: blogdown, bookdown, pkgdown, etc.
- You can use GitHub as a search engine to see how people write their `Makefile`s and how they use functions in a given language
- You can add a license to your repo upon creation or later by adding a file called LICENSE.md
  - GitHub provides you a list to select licenses from
  - Think about commercial/non commercial, share alike/not
  - See https://choosealicense.com/ for help with picking a license
- [Happy Git with R](http://happygitwithr.com/) by [Jenny Bryan](http://github.com/jennybc)

---

## Make tips and resources

- Some projects you can outline well initially and start with a Makefile
- Others you'll want to start working in an R Markdown document and then break it up into pieces and use `make` to glue the pieces back together
- Thinking about the folder structure(s) helps and leveraging tools like `here` helps
- Leverage the community, you are not alone in dealing with these types of problems
  - Twitter, Stack Overflow, etc.
  - Scientific computing is a large tent - look beyond R for ideas

---
class: middle, center

## Thanks <br/> Enjoy JSM 2019!